language: php

sudo: false

php:
  - 7.4
  - 8.0
  - 8.1

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 composer install -n

script:
  - vendor/bin/phpunit -c Tests/
  - vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=vendor .
